### ISSUE TITLE
Add support for Decent Holograms instead of Holographic Displays

### ISSUE THREAD

**Issue by RE4ERKA** [M0diis/SimpleBombs#1]
Decent Holograms works faster than Holographic Displays.

I use Decent Holograms on my server and wouldn't want to put a second plugin on Holograms.

**Comment by M0diis** [comment]
Hey.

There is an unreleased version with DecentHologram support.
There seems to be some issues with Gradle CI workflow.

I'll keep you up to date.

**Comment by M0diis** [comment]
Please try this artifact from the workflow in the link below:
- https://github.com/M0diis/SimpleBombs/actions/runs/2266822894

**Comment by RE4ERKA** [comment]
Yes, it works.

Thanks.

**Comment by M0diis** [comment]
Glad the issue is resolved.

I will release a full update in the near future.
